# nixpacks.toml

# Add system packages needed to build mysqlclient
[phases.setup]
aptPkgs = ["python3-dev", "default-libmysqlclient-dev", "build-essential"]

# Optional: Add WeasyPrint dependencies if you need PDF generation
# aptPkgs = ["python3-dev", "default-libmysqlclient-dev", "build-essential", "libpango-1.0-0", "libcairo2", "libgdk-pixbuf-2.0-0", "libffi-dev"]

# Optional: Define start command if NOT using Procfile
# [start]
# cmd = "gunicorn e_voting.wsgi --log-file -"