# nixpacks.toml

[phases.setup]
aptPkgs = ["python3-dev", "libmysqlclient-dev", "build-essential"]

# If you also need WeasyPrint dependencies, add them back here:
# aptPkgs = ["python3-dev", "libmysqlclient-dev", "build-essential", "libpango-1.0-0", "libcairo2", "libgdk-pixbuf-2.0-0", "libffi-dev"]

# [start]
# # If you defined a start command here and are also using a Procfile,
# # ensure only one is defining the start command.
# # Prefer Procfile for web/release commands.