# nixpacks.toml

# Define phases (optional, Nixpacks usually detects Python)
# [phases.setup]
# nixPkgs = [...] # System-wide packages if needed before Python setup

# Install system libraries needed by WeasyPrint
[phases.install]
aptPkgs = ["libpango-1.0-0", "libcairo2", "libgdk-pixbuf-2.0-0", "libffi-dev"] # Common Debian/Ubuntu names

# Define build command (optional if handled elsewhere)
# [phases.build]
# cmds = ["python manage.py collectstatic --noinput"]

# Define start command (if not using Procfile)
# [start]
# cmd = "gunicorn e_voting.wsgi --log-file -"